version: "3"
services:
  redis:
    image: 'redis:alpine'
    container_name: keda-redis
    ports:
      - "6379:6379"
  postgres:
    container_name: keda-postgresql
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - keda-parking:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking
      TIME_ZONE: "Asia/Jakarta"
      TZ: "Asia/Jakarta"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: keda-backend
    env_file: .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: parking
      DB_HOST_LOG: postgres
      DB_PORT_LOG: 5432
      DB_USER_LOG: postgres
      DB_PASSWORD_LOG: postgres
      DB_DATABASE_LOG: parking
      REDIS_CONNECTION: local
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TIME_ZONE: "Asia/Jakarta"
      TZ: "Asia/Jakarta"
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    command: sh -c "echo 'Please Wait Until Database Created!' && sleep 10 && npm run migrate && adonis serve --dev"
  nginx:
    build: ./nginx
    container_name: keda-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  keda-parking: